- name: Pushing datapatch apply script
  ansible.builtin.template:
    src: 19c_rdbms_datapatch.sh.j2
    dest: "{{ remote_bin }}/{{ env }}_{{target}}_19c_rdbms_datapatch.sh"
    mode: 0744
    force: yes
  with_items: "{{ remote_bin }}"

- name: Execute Oracle OPATCH patching script
  ansible.builtin.shell: 
    sudo su - {{ soft_user }} -c "sh {{ remote_bin }}/{{ env }}_{{target}}_19c_rdbms_datapatch.sh | tee -a {{ remote_logs }}/{{ env }}_{{target}}_19c_rdbms_datapatch.log"
  register: reg_output

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: reg_output.stdout_lines
    verbosity: 0