- name: Pushing database patching script
  ansible.builtin.template:
    src: 19c_rdbms_patch_oh.sh.j2
    dest: "{{ remote_bin }}/{{ env }}_{{target}}_19c_rdbms_patch_oh.sh"
    mode: 0744
    force: yes
  with_items: "{{ remote_bin }}"

- name: Execute Oracle database patching script
  ansible.builtin.shell: 
    sudo su - {{ soft_user }} -c "sh {{ remote_bin }}/{{ env }}_{{target}}_19c_rdbms_patch_oh.sh | tee -a {{ remote_logs }}/{{ env }}_{{target}}_$(date '+%Y%m%d_%H%M%S')_19c_rdbms_patch_oh.log"
  register: reg_output

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: reg_output.stdout_lines
    verbosity: 0