- name: "Pushing OPatch checkconflict script"
  ansible.builtin.template:
    src: rdbms_checkconflict.sh.j2
    dest: "{{ remote_bin }}/{{ target }}_checkconflict.sh"
    mode: 0755
    force: yes

- name: "Execute Oracle Checkconflict script"
  ansible.builtin.shell: 
    sudo su - {{ soft_user }} -c "sh {{ remote_bin }}/{{ target }}_checkconflict.sh | tee -a {{ remote_logs }}/{{ target }}_checkconflict_$(date '+%Y%m%d_%H%M%S').log"
  register: reg_output

- name: "Print return information from the previous task"
  ansible.builtin.debug:
    var: reg_output.stdout_lines
    verbosity: 0
