# Luke Davies / Pythian / Oracle RDBMS patch automation

# - name: Pushing OPatch apply script
#   ansible.builtin.template:
#     src: 19c_rdbms_patch_opatch.sh.j2
#     dest: "{{ remote_bin }}/{{ env }}_{{target}}_19c_rdbms_patch_opatch.sh"
#     mode: 0744
#     force: yes
#   with_items: "{{ remote_bin }}"

# - name: Execute Oracle OPATCH patching script
#   ansible.builtin.shell: 
#     sudo su - {{ soft_user }} -c "sh {{ remote_bin }}/{{ env }}_{{target}}_19c_rdbms_patch_opatch.sh | tee -a {{ remote_logs }}/{{ env }}_{{target}}_$(date '+%Y%m%d_%H%M%S')_19c_rdbms_patch_opatch.sh"
#   register: reg_output

# - name: Print return information from the previous task
#   ansible.builtin.debug:
#     var: reg_output.stdout_lines
#     verbosity: 0

### LUKE Davies scripting

- name: Stage LD_Oracle Tool Target
  ansible.builtin.copy:
    src: oracle_patching-main.zip
    dest: "{{ remote_bin }}"
    #owner: root
    #group: root
    mode: '0644'
    backup: yes
  
- name: Extract LD_Oracle Tool
  ansible.builtin.unarchive:
    src: "{{ remote_bin }}/oracle_patching-main.zip"
    dest: "{{ remote_bin }}"
    remote_src: yes

- name: Creates logs directory
  file:
    path: "{{ remote_bin }}/oracle_patching-main/logs"
    state: directory 
    mode: 0777

- name: Push op.cfg configuration
  ansible.builtin.template:
    src: op.cfg.j2
    dest: "{{ remote_bin }}/oracle_patching-main/config/op.cfg"
    mode: 0744
    force: yes
  with_items: "{{ remote_bin }}"

  ### instructions:
- name: Pushing RDBMS functions
  ansible.builtin.template:
    src: functions.sh.j2
    dest: "{{ remote_bin }}/functions.sh"
    mode: 0744
    force: yes
  with_items: "{{ remote_bin }}"

- name: Pushing RDBMS execute
  ansible.builtin.template:
    src: rdbms_patch.sh.j2
    dest: "{{ remote_bin }}/{{ env }}_{{target}}_rdbms_patch.sh"
    mode: 0744
    force: yes
  with_items: "{{ remote_bin }}"

- name: Execute RDBMS execute patching script
  ansible.builtin.shell: 
    sudo su - {{ soft_user }} -c "sh {{ remote_bin }}/{{ env }}_{{target}}_rdbms_patch.sh | tee -a {{ remote_logs }}/{{ env }}_{{target}}_$(date '+%Y%m%d_%H%M%S')_rdbms_patch.log"
  register: reg_output

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: reg_output.stdout_lines
    verbosity: 0