# loads variables
- include_tasks: "setvars.yml"

- name: "Display Variables"
  debug: 
    msg:
    - "Local Staging Directory    :  {{ local_stage }}"
    - "Local Logging Directory    :  {{ local_log }}"
    - "MOS Username               :  {{ mos_user }}"
    - "Oracle software user       :  {{ soft_user }}"
    - "Oracle group               :  {{ soft_group }}"
    - "Remote Staging Directory   :  {{ remote_stage }}"
    - "Remote logging directory   :  {{ remote_logs }}"
    - "Remote bin directory       :  {{ remote_bin }}"
    - "Oracle Home location       :  {{ oracle_home }}"
    - "Oracle base location       :  {{ oracle_base }}"
    - "Environment                :  {{ env }}"
    - "Target                     :  {{ target }}"
    - "Cycle                      :  {{ cycle }}"
