---
- name: "Load global variables if present for Customer"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "../../../vars/global.yml"
      skip: True

- name: "Load global variables if present for Environment"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "../../../vars/{{ env }}/global.yml"
      skip: True

- name: "Load target variables if present for Oracle Home"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "../../../vars/{{ env }}/{{ target }}.yml"
      skip: True

- name: "Load Patching Scenario / Cycle"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "../../../cycles/{{ cycle }}.yml"
      skip: True


