- name: Pushing ADOP functions
  ansible.builtin.template:
    src: functions.sh.j2
    dest: "{{ remote_bin }}/functions.sh"
    mode: 0744
    force: yes
  with_items: "{{ remote_bin }}"

- name: Pushing ADOP execute
  ansible.builtin.template:
    src: adop.sh.j2
    dest: "{{ remote_bin }}/{{ env }}_{{target}}_adop.sh"
    mode: 0744
    force: yes
  with_items: "{{ remote_bin }}"

- name: Execute ADOP execute patching script
  ansible.builtin.shell: 
    sudo su - {{ soft_user }} -c "sh {{ remote_bin }}/{{ env }}_{{target}}_adop.sh | tee -a {{ remote_logs }}/{{ env }}_{{target}}_$(date '+%Y%m%d_%H%M%S')_adop.sh.log"
  register: reg_output

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: reg_output.stdout_lines
    verbosity: 0