
# Patching Playbook
- hosts: all
  tasks:
    - name: SetVars
      include_role:
        name: setvars

    - name: Confirm Environment Variables
      pause:
        prompt: "Please verify Environment Variables printed above, type yes to confirm"
      register: confirm_env

    - name: Initiate Patching
      include_role:
        name: 19c_rdbms_patch_oh
      when: confirm_env.user_input | bool
