# Patching Playbook
- hosts: all
  tasks:
    - name: SetVars
      include_role:
        name: setvars

    - name: Confirm Environment Variables
      pause:
        prompt: "Please verify Environment Variables printed above, type yes to confirm"
      register: confirm_env

    - name: Initiate Database Stop
      include_role:
        name: stop
      when: confirm_env.user_input | bool

    - name: Initiate opatch patching
      include_role:
        name: 19c_rdbms_patch_opatch

    - name: Initiate Database patching
      include_role:
        name: 19c_rdbms_patch_oh

    - name: Startup Database
      include_role:
        name: startup

    - name: Run Datapatch if required
      include_role:
        name: datapatch
      when: datapatch_required